// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ExtraInfo struct {
	RemindTime *string `json:"remindTime"`
}

type InputExtraInfo struct {
	RemindTime string `json:"remindTime"`
}

type InputTodo struct {
	Text     string          `json:"text"`
	UserName string          `json:"userName"`
	Done     *bool           `json:"done"`
	Extra    *InputExtraInfo `json:"extra"`
}

type InputUser struct {
	Name   string   `json:"name"`
	Height *float64 `json:"height"`
	Hobby  []string `json:"hobby"`
	Age    int      `json:"age"`
}

type Todo struct {
	ID    string     `json:"id"`
	Text  string     `json:"text"`
	Done  bool       `json:"done"`
	User  *User      `json:"user"`
	Extra *ExtraInfo `json:"extra"`
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Height *float64 `json:"height"`
	Hobby  []string `json:"hobby"`
	Age    int      `json:"age"`
}
